# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy Node.js app to Azure Web App - strapi-poc-kc

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Node.js version
#         uses: actions/setup-node@v1
#         with:
#           node-version: '18.x'

#       - name: Run install
#         uses: borales/actions-yarn@v4
#         with:
#           cmd: install # will run `yarn install` command


#       - name: Build production bundle
#         uses: borales/actions-yarn@v4
#         with:
#           cmd: build # will run `yarn build:prod` command
      
#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'strapi-poc-kc'
#           slot-name: 'Production'
#           package: .
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_40867F05C795425EA3A77C25AAF2F6A9 }}
